## **Who Is In The Third Place?**

Create a function whose name is ```third_place``` that does the following: 

Given a list of test score and a list of participants name. The desired output would be the name of the participant who gets the 3rd best score. The rule of determining the order of the best score is as follows:
- Higher score is better
- In case of multiple participants having the same test score, they can occupy the same ranking value. For example, if 2 participants scored 100, then both of them occupy the first place. 

The first input of the function is the name list, and the second input to the function is the score list.

##### Example 1:

Input:

names = [Andi, Budi, Charlie, Dilan, Echa]

score = [80, 90, 95, 100, 85]

This means, Andi gets 80, Budi gets 90, Charlie gets 95, Dilan gets 100, and Echa gets 85. The first best score is 100, and Dilan gets it. The second best score is 95, and Charlie gets it. The third best score is 90, and Budi gets it. So, our output should be Budi.

Output: 'The third winner: Budi'.

When we run ```third_place(names, score)```, the output will be 'The third winner: Budi'.

##### Example 2:

Input:

names = [Andi, Budi, Charlie, Dilan, Echa]

score = [80, 80, 80, 100, 90]

This means, Andi, Budi, and Charlie gets 80, Dilan gets 100, and Echa gets 90. The third best score is 80, and our output should list ALL of the participants who get 80. 

Output: 'The third winner: Andi, Budi, Charlie'.

When we run ```third_place(names, score)```, the output will be 'The third winner: Andi, Budi, Charlie'.


##### Example 3:

Input:

names = [Andi, Budi, Charlie, Dilan, Echa, Fanya]

score = [80, 90, 90, 100, 100, 80]

The first best score (first winner) is 100 - Dilan and Echa shared this position. The second best score (second winner) is 90 - Budi and Charlie shared this position. The third best score (third winner) is 80, and it is shared by Andi and Fanya. So, our output should be Andi and Fanya.

Output: 'The third winner: Andi, Fanya'.

In [10]:
import pandas as pd

In [11]:
# create a function whose name is third_place
def third_place(names, score):
 
 # create a dataframe from list of names and score
 data ={'names': names[0:], 'score': score[0:]}
 df = pd.DataFrame(data)

 # sort the value of score in descending order (from the highest value to lowest value) and re-labeled the index from 0, 1, ..
 df = df.sort_values('score', ascending=False, ignore_index=True)

 # removing duplicates value of score in dataframe to get the exact value of the third top score and re-labeled the index from 0, 1, ..
 df_score = df.drop_duplicates(subset=['score'], ignore_index=True)

 # define the value of third top score by select spesific value in column score and row index number 2 
 third_top_score = df_score['score'].loc[2]

 # select rows of dataframe where 'score' is same with value of third top score that we've define before
 third_place = df[df['score']==third_top_score]

 # take the names in third_place dataframe that we've define before and change it into list form
 names_third_place = list(third_place['names'])

 # output
 # print element in names_third_place list
 print('the third winner : ', ', '.join(names_third_place))

In [14]:
names = ['Andi', 'Budi', 'Charlie', 'Dilan', 'Echa']
score = [80, 90, 95, 100, 85]

third_place(names, score)

the third winner :  Budi

In [15]:
names = ['Andi', 'Budi', 'Charlie', 'Dilan', 'Echa']
score = [80, 80, 80, 100, 90]

third_place(names, score)

the third winner :  Andi, Budi, Charlie

In [16]:
names = ['Andi', 'Budi', 'Charlie', 'Dilan', 'Echa', 'Fanya']
score = [80, 90, 90, 100, 100, 80]

third_place(names, score)

the third winner :  Andi, Fanya